# Nombre de la aplicación Spring Boot se usa internamente para identificar la aplicación
spring.application.name=biblioteca-application

# Puerto donde se ejecutará el servidor
# http://localhost:8081
server.port=8081

# URL de conexión a MySQL
# jdbc:mysql:// -> protocolo JDBC para MySQL
# localhost -> servidor de base de datos
# 3306 -> puerto de MySQL
# pokemon -> nombre de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca

# Usuario de MySQL
spring.datasource.username=root

# Contraseña del usuario MySQL (vacío significa que root no tiene contraseña)
spring.datasource.password=

# Driver JDBC que permite conectar Java con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto SQL que utilizará Hibernate
# Hibernate adapta automáticamente las consultas a MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Muestra las consultas SQL en la consola (muy útil para aprender y depurar)
spring.jpa.show-sql=true

# Gestión automática de tablas por Hibernate
# update:
# - crea tablas si no existen
# - actualiza columnas automáticamente
# - NO borra datos existentes
#
# Otros valores:
# create       -> borra y crea todo cada vez
# create-drop  -> crea al iniciar y borra al cerrar
# validate     -> solo comprueba estructura
# none         -> no hace nada
spring.jpa.hibernate.ddl-auto=create
